apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
resources:
  - postgres-keycloak-job.yaml
  - postgres-tableties-job.yaml
configMapGenerator:
  - name: init-tableties.sql
    files:
      - init-tableties.sql